### ISSUE TITLE
オフハンドから食べ物を食べるとインベントリに返ってくる

### ISSUE THREAD

**Issue by tanakanata** [sk7z-xyz/FastUse#5]
環境
Minecraft 1.17.1

内容
・インベントリに空きがある状態でオフハンドからものを食べると、インベントリに1つ返ってきます
・インベントリに空きが無かった場合は2つアイテムが消費されます

**Comment by sk7z-xyz** [comment]
直した後にIssue建ってることに気づいた
https://github.com/sk7z-xyz/FastUse/commit/090d7f724aa37be7ad0573ec7d17b0d6a2afc2ec
